### ISSUE TITLE
Add ES6/browserify/vuejs docs to README?

### ISSUE THREAD

**Issue by OmgImAlexis** [pimterry/loglevel#100]
Since more and more people are starting to use Vuejs it may be an idea to add something to the docs to let them know how to get this library working.

```
import * as log from 'loglevel';
window.log = log.noConflict();
```

**Comment by pimterry** [comment]
I don't know vue. I'm surprised by the above though - why do you need to do that, why don't you just import log and then use it like any other library?

**Comment by OmgImAlexis** [comment]
You need to import all the functions otherwise none of the log.* functions works.
For example `log.info()` only works after importing info from `loglevel`.

You also need window.log to use it within all of your .vue files otherwise it'll only work in the single file/component that it's imported into. If the user wanted they could just import it and bind `log.noConlict()` to the Vue method field but that would limit log to only be usable for that single component.

**Comment by mibanez** [comment]
Still not working for me (i'm using `vue-cli`). Seems to be that `loglevel` has not access to console and every log method end up being the default method `noop` (function() {})

**Comment by OmgImAlexis** [comment]
@mibanez did you use `import * as log from 'loglevel';`? If you just import loglevel itself then nothing it set, that's why you end up with noop.

**Comment by julestruong** [comment]
@OmgImAlexis not working either for me, did you actually test your code ? :/

**Comment by OmgImAlexis** [comment]
Yes and I use it for multiple projects.

**Comment by julestruong** [comment]
@OmgImAlexis worked , sorry

**Comment by pimterry** [comment]
Glad to hear that all worked out. I'm not totally sure I'm following the above as a non-vue user. Are there some basic instructions for this vue setup that should be in the readme? If any of you want to put together a PR to add a short snippet for this (under [`Setting it up`](https://github.com/pimterry/loglevel#setting-it-up)), I'd be happy to include it.

**Comment by OmgImAlexis** [comment]
@pimterry just including something like this would work; and it's for ES6 not vue specifically.

In ES6 make sure to import the whole package.
The last line only applies while using ES6 in the browser as allows the use of log anywhere in your app.
```
import * as log from 'loglevel';
window.log = log.noConflict();
```
