### ISSUE TITLE
Grunt tasks broken

### ISSUE THREAD

**Issue by tauren** [pimterry/loglevel#101]
I'm running into all sorts of problems getting dist to build. Running `./node_modules/.bin/grunt dist` fails. Once I fix an issue, another one crops up.

1. jshint would fail, so I updated to the latest `grunt-contrib-jshint`
2. jshint ran, but several errors in `lib/loglevel.js`, so I fixed them
3. Now phantomjs won't run in task `jasmine:requirejs`

I tried updating all dependencies to the latest versions. Now I'm not getting an error, but PhantomJS times out with a message saying there may be an async test that never finishes.

Would really help if `git clone ...; npm install; grunt dist` just worked... 

Also it would be nice if it didn't depend on `grunt` being installed installed globally. I suggest adding `"dist": "./node_modules/.bin/grunt dist"` to the `package.json` scripts and building with `npm run dist`.

**Comment by pimterry** [comment]
Sorry for the delay! Totally agree this should work. Now fixed, and I've added npm aliases for everything too, using a local grunt. For me clone -> install -> `npm run dist` now all works reliably. Let me know if you (or anybody else!) has any other trouble with this.
