### ISSUE TITLE
Is there any releases planned for this library? Is this forum active?

### ISSUE THREAD

**Issue by KalpanaPagariya** [pimterry/loglevel#102]

**Comment by pimterry** [comment]
I do keep an eye on everything here, although not quite a thoroughly as I'd like (I've been meaning to sort out https://github.com/pimterry/loglevel/issues/101 for example, but it's fiddly and never _urgent_ - PRs welcome!).

I'm generally interested in improving and extending loglevel, but the number 1 goal for this library was to be a very simple and very reliable minimal logging tool, and it already does that fine. There are already many more complex heavy duty logging libraries, which I don't want to turn this into. Until something changes, like some clearly valuable improvements appearing (in line with that goal), or new major bugs coming up, I don't have any major further releases planned right now, no.
