### ISSUE TITLE
output of log data

### ISSUE THREAD

**Issue by xricj** [pimterry/loglevel#103]
Hello.
I have a question regarding the output of the logging data. 
Using loglevel library I can see the logging data to the browser console.  Are those data saved in any file?
 I would like to have these logging data saved in a text file for example, instead of just print them in the browser console. 

PS : I am completely new in javascript and html scripts so my question maybe is silly..
Thanks

**Comment by pimterry** [comment]
Hi @xricj!

No, this data isn't saved to a file. It's generally difficult to do that inside webpages, as they're not allowed to write files to your computer.

If you're just looking to make the messages more accessible between page loads, there's a 'preserve log' button in Chrome that will ensure the log in the browser isn't cleared for you, until you close the tab.

If you're looking for long-term logging persistence, you'll need to do something more complicated. That isn't something loglevel does by itself. Typically you'd do this by having a server somewhere (probably on your own machine to for early development), and you'd use a plugin like [serverSend](https://github.com/artemyarulin/loglevel-serverSend) with loglevel, to send all your logs to that server. You'll need to set up a server yourself to receive these log messages and save them to a file though.
