### ISSUE TITLE
How can I display loglevel on each message?

### ISSUE THREAD

**Issue by aguynamedben** [pimterry/loglevel#113]
Is there a way to display the loglevel for each message so when messages are logged in my console it's easy to tell which level it's at?

Code:
```
log.setLevel('debug');
log.debug('This is a debug message');
```

Console Output:
```
This is a debug message
```

Desired Console Output:
```
DEBUG: This is a debug message
```

**Comment by asasine** [comment]
A common way is to use plugins. The one I use is linked in the readme https://github.com/kutuluk/loglevel-plugin-prefix

**Comment by aguynamedben** [comment]
Oh, cool sorry, missed that... closing. Thanks for the help, I love this library and have used it on multiple projects over the past few years.
