### ISSUE TITLE
New plugin

### ISSUE THREAD

**Issue by gzoreslav** [pimterry/loglevel#115]
Hi,

I've just created the new plugin https://www.npmjs.com/package/loglevel-plugin-server for sending data to the server. It is similar to existing ones, but with some improvements. Could you please add link to the README?

Thank you,
Zoreslav

**Comment by pimterry** [comment]
It'd be easier if you just open a PR yourself for the change you'd like, feel free. You'll be able to explain it much more clearly than I will!
