### ISSUE TITLE
Improve first README code snippet example

### ISSUE THREAD

**Issue by lekkas** [pimterry/loglevel#118]
The first code example in the README suggests to use 

```
var log = require('loglevel');
log.info("unreasonably simple");
```

Given that the default loglevel is `warn` (as mentioned in the README) this snippet will need some additional loglevel setup calls to actually print a message. 

I guess this example could be changed to either match the default loglevel (`log.warn`) or include a suggested setup method (`log.setDefaultLevel()` maybe).

Happy to send a README PR if this is acknowledged as an actual issue

**Comment by pimterry** [comment]
Good point, thanks! Fixed by just moving everything to `log.warn`
