### ISSUE TITLE
Doesn't seem to work with JSPM

### ISSUE THREAD

**Issue by selfagency** [pimterry/loglevel#122]
Trying to use loglevel with JSPM (System.JS). 

My import statement:
`import * as log from 'loglevel'`

My test:
`log.info('test')`

The result:
![screenshot 2018-08-03 11 16 33](https://user-images.githubusercontent.com/2541728/43650896-f509ceb6-970e-11e8-81be-66752a2f9267.png)

**Comment by pimterry** [comment]
I don't know anything about JSPM or System.JS I'm afraid. Loglevel is built as a UMD module, so you should use whatever the standard way to import that is in your environment. That code looks reasonable to me in theory though.

You might get some clues on what's going on if you look at the value of `log` itself though, it's not clear what that is from the above.
