### ISSUE TITLE
No DEMO link in readme

### ISSUE THREAD

**Issue by ttodua** [pimterry/loglevel#123]
the readme is missing one of the most important thing - it doesnt contain demo.

for example, the BlackBird.js demo - http://demo.jb51.net/js/Blackbird/index.html

see how well it demonstrates the behavior.

**Comment by pimterry** [comment]
It's not the most thrilling library for demos, but I can see how a working live implementation you can play with might be useful. I'd happily accept PRs for this.

**Comment by hirako2000** [comment]
I tried to submit a PR, but I'm having issues actually getting a demo to run as expected.
Here is the value of demos:  Demonstrate basic functionalities. I can't get tracing to work even though I set the level to tracing. A demo can best show how enabling tracing works as I surely do something wrong.

**Comment by hirako2000** [comment]
Do you see the tracing call in the  console tab ? I don't with  latest desktop chrome build for latest osx.

I wouldn't say it's a library bug. Just trying to get close to a demo url we could place on the reademe to keep new users happy.
If it works for you, just merge the codepen. Or provide a better one than the rudimentary statements I placed in there.

**Comment by bladeski** [comment]
@pimterry - This could probably be closed now!
