### ISSUE TITLE
Blocked by uBlock Origin (EasyPrivacy)

### ISSUE THREAD

**Issue by peyao** [pimterry/loglevel#132]
Just raising awareness to this as it's causing problems for some using loglevel:

https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt#L2309

For apps including the dist/loglevel.js directly as a script tag, trying to use loglevel may throw.

I opened a PR on their repo: https://github.com/easylist/easylist/pull/3463
But you may want to follow up.

**Comment by pimterry** [comment]
Ah, just to confirm: you've closed this because the linked PR is merged, so this is no longer an issue, is that right? Amazing if so, thanks for doing that 👍

**Comment by peyao** [comment]
Right, no problem.
