### ISSUE TITLE
Set log level recursively

### ISSUE THREAD

**Issue by muuvmuuv** [pimterry/loglevel#134]
I don't know if this is already possible, couldn't find anything in the docs but this would be very useful. I expect something like `log.setGlobalLevel()`, so all log level instances would be affected and not just one.

I have an application where users have the option to set debugging on and off while the app is running (VS Code extension). In a function called `checkConfig` I check for the config and if they want to debug and then set the log level to debug. This works great for the top level logger but all loggers inside my functions which are called with `logger.getLogger('updateConfig')` are not affected.

**Comment by pimterry** [comment]
That makes sense, I can definitely see the use case.

You're right that it's not possible right now directly, but you can do this fairly easily with `log.getLoggers()` to get all loggers, and then just calling `setLevel` on each of the loggers returned. I haven't tested it, but in theory that should work very easily. Can you give that a go and let me know if it solves the problem for you?

**Comment by muuvmuuv** [comment]
@pimterry I "don't" have such function. I'm using TypeScript and have notices that the types do not match the latest API of your lib. Maybe they should be updated first? 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/loglevel/index.d.ts

**Comment by pimterry** [comment]
Aha, I see. It should definitely exist at runtime regardless - if you cast `log` to `any`, and then try it, does that work for you?

Those type definitions should definitely be updated anyway, so that this works normally. I'll take a look at that (and actually probably pull them back into this package directly) some time later this week.

**Comment by muuvmuuv** [comment]
I'm really a fan of DefinitelyTyped but IMO keeping typings in the package repo makes more sense especially when it comes to issue tracking and fast updates.

**Comment by muuvmuuv** [comment]
Yep this is working but a little messy :D 

```ts
function setGlobalLevel(level: any) {
  const loggerList = (logger as any).getLoggers()
  if (loggerList.length <= 0) {
    return
  }
  console.log(loggerList)
  Object.keys(loggerList).forEach((l: any) => {
    loggerList[l].setLevel(level)
  })
}
```

**Comment by pimterry** [comment]
All done! @muuvmuuv if you update to loglevel@1.6.2 and uninstall `@types/loglevel`, you should pick up the new type definitions, which includes getLoggers, and this should work nicely.

By the way, the `length` check in your example probably doesn't work (`loggerList` is an object, not a list), and isn't needed anyway (`forEach` will do nothing if the list is empty), so I think you can simplify this down to just:

```ts
function setGlobalLevel(level: any) {
  Object.values(logger.getLoggers()).forEach((logger) => {
    logger.setLevel(level)
  })
}
```

Assuming that that works, and given that that's pretty simple, I'm going to close this for now. Unless there's mountains of people asking for specific support for this, I don't think there's need for built-in functionality.
