### ISSUE TITLE
loglevel.trace() does not print message in IE11

### ISSUE THREAD

**Issue by CaitlinWeb** [pimterry/loglevel#138]
@pimterry Kudos for the awesome library you've created. Thank you 😄 I've got a hopefully small request that I don't think has been addressed before.

### Issue

On my current project where I'm trying to use loglevel we unfortunately need to support IE11. Ideally it would log everything similarly to Chrome and other modern browsers. Of course, IE11 treats console.trace differently.

When using `loglevel.trace("message")` I'm not able to see the message. Instead, it literally prints "console.trace()" followed by the stack information.

### Expected result

When `console.trace` won't output a log message, call `console.log` with the message before `console.trace`. 

Even if this is only a fix for IE11 I would be satisfied (besides, it's probably the only browser that doesn't handle it correctly).

**Comment by CaitlinWeb** [comment]
@pimterry I plugged that function in where I was using a `loglevel.trace()` but it didn't work, though it's close. `Error.stack` is undefined in IE11. I tried this and it worked:

```javascript
function traceForIE() {
    console.log.apply(console, arguments)
    console.trace()
}
```

It does include the wrapper function in the stack trace but I think that's acceptable, as long as the function is named appropriately. The rest of the stack was the same as just `console.trace()`.

**Comment by pimterry** [comment]
Hi @CaitlinWeb, sorry about the delay - I've just pushed a change (https://github.com/pimterry/loglevel/commit/feeaeb876c69a82a11422996bb9fe250c8ad282b) to make this work in IE11.

Can you test that out, and let me know if it solves the issue for you? You'll need to use `lib/loglevel.js` from the current master: https://github.com/pimterry/loglevel/blob/feeaeb876c69a82a11422996bb9fe250c8ad282b/lib/loglevel.js.

**Comment by CaitlinWeb** [comment]
@pimterry No problem. Tried it out and it worked in IE11. Example output:

![trace-in-IE11](https://user-images.githubusercontent.com/6975769/68232406-02af5600-ffcb-11e9-9baf-e09dc7e57be8.png)

This is fine for our use case. Lemme know when this is in a release and I'll close this Issue. 😃

**Comment by pimterry** [comment]
Now released! This is available in v1.6.6. Thanks for the report & the help :smile:

**Comment by CaitlinWeb** [comment]
@pimterry Was just browsing through the documentation (to explain loglevel to team members) and noticed it says:

>For example, log.trace(msg) in IE11, and Firefox before version 64, prints the stacktrace by itself and doesn't include your message (see #84 & #138).

Might wanna update that to say what version includes the message for IE11 👍 

And thanks for working with me on this, greatly appreciate the quick turnaround!

**Comment by pimterry** [comment]
Good catch! Thanks @CaitlinWeb, I've just updated it.
