### ISSUE TITLE
How to dynamically control log level

### ISSUE THREAD

**Issue by devamchakrabarty** [pimterry/loglevel#145]
Is there any example for the following:
> then run log.setLevel("trace") in your console to turn it all back on for a furious debugging session

I couldn't find a way to intuitively change the log level at runtime.

**Comment by pimterry** [comment]
Can you tell me any more about what you're trying to do? Do you want to change the level at runtime manually for one-off debugging, or control the level at runtime in your application code?

All you should need to do either way is call `log.setLevel(...)` to change the level. That's all that's required. Is that not working for you?

**Comment by devamchakrabarty** [comment]
Yes, I'm looking for a way to change the level at runtime manually for one-off debugging (troubleshooting) tricky production issues. I tried `log.setLevel(...)` in the browser's console window but it complained about `log` not defined. I also changed the log level in the browser's local storage but that didn't have any effect.

In our code we've set the log level to be 'Warn' for production deployments, but I'm looking for a way to change that at runtime.

**Comment by pimterry** [comment]
Ok, to do that you'll need to expose loglevel as a global. If you import loglevel with a bundler then it doesn't do that for you by default, so you'll need to either a) work out a way to require packages from your bundle at runtime, or b) explicitly expose `log` as a global. The latter means adding `window.log = log`, wherever it is that you're importing & configuring loglevel in your application code.

**Comment by devamchakrabarty** [comment]
Thanks for your response. I don't think it is as easy as I thought it should be. 
We're building an add-in for Microsoft Outlook which is a single page nodejs microsite within an iframe. We've added loglevel [directly to our web page](https://github.com/pimterry/loglevel#directly-in-your-web-page) and tried the window.log approach (option b in your comment above) but that didn't work. Since the main page is external, we're not sure whether a [Window.PostMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) can solve this problem for us.

**Comment by devamchakrabarty** [comment]
Thanks @pimterry, option b) from your comment above works for us. 👍
