### ISSUE TITLE
React Native production mode app crashing bug

### ISSUE THREAD

**Issue by comountainclimber** [pimterry/loglevel#148]
When compiling a production binary in React Native / expo using loglevel something causes the following application crashing type error:

```
'RCTFatalException: Unhandled JS Exception: TypeError: this.methodFactory is not a function. (In 'this.methodFactory(a,t,n)', 'this.methodFactory' is undefined)', reason: 'Unhandled JS Exception: TypeError: this.methodFactory is not a function. (In 'this.methodFactory(a,t,n)', 'this.methodFactory' is undefined), stack:
```

To reproduce this you can just create an expo application install loglevel and run `react-native run-ios --configuration=release`

NOTE: loglevel works perfectly fine in development mode and any other non production environment when working with expo/react-native as shown in the image below:
<img width="1712" alt="Screen Shot 2020-08-06 at 7 15 49 AM" src="https://user-images.githubusercontent.com/13072035/89536196-c5276580-d7b4-11ea-9582-751ffdedb319.png">

**Comment by pimterry** [comment]
You've closed this issue - @comountainclimber is that because you've shown that it's not a loglevel bug, or because you've found an alternative/workaround?

**Comment by comountainclimber** [comment]
@pimterry it appears to be working totally fine I created a demo below:
https://github.com/comountainclimber/rn-loglevel-example

Production build works fine and I am no longer seeing the error with `react-native run-ios --configuration=release`

**Comment by pimterry** [comment]
Ok, great! Thanks for letting me know
