### ISSUE TITLE
Support `loglevel.getLogger(Symbol())`

### ISSUE THREAD

**Issue by vvanpo** [pimterry/loglevel#151]
Passing a string to `getLogger` does not ensure that your logger won't collide with existing loggers, leading to unexpected behaviour. In tests or for libraries that don't know much about what environment they're running in, it can be helpful to use `Symbol` to ensure there can never be collisions.

**Comment by pimterry** [comment]
Great suggestion! I've added support for that in https://github.com/pimterry/loglevel/commit/ae3a282a02ce377edad43e129c83a6d53cd7ed0c.

The one tricky bit is that we previously used names for log level persistence: in a browser, the level for each logger is stored as `loglevel:${logname}` in local storage. We can't uniquely do that for symbols, so I've just dropped persistence for symbol-named loggers entirely, we effectively treat them as fresh every time. Can you take a look at at that, and let me know if that would work for you?

**Comment by vvanpo** [comment]
Thanks for the quick turnaround! And yes, that definitely works for me.

**Comment by dixdiydiz** [comment]
@pimterry 
index.d.ts should fix:
  getLogger(name: string): Logger;
to 
  getLogger(name: string | symbol): Logger;

**Comment by pimterry** [comment]
Good catch, thanks @dixdiydiz! Now fixed in v1.7.1.

In future do feel free to throw in a PR, I'm very happy to merge tiny fixes like that straight away.
