### ISSUE TITLE
Log.error should stringy the error object

### ISSUE THREAD

**Issue by yesparthasarathy** [pimterry/loglevel#159]
we are using the log.error method to log the error. some time error object has some circular reference, which causing issue on the application level. please advice

**Comment by pimterry** [comment]
Loglevel is intentionally _not_ going to do this: the goal is to be a simple wrapper around `console.log` to let you control logging levels dynamically from your code, and to make it behave consistently across different platforms (so if something consistently fails everywhere when using console.log, then it should also fail when using loglevel).

You should do whatever you'd normally do when logging with console.log directly.

If you're seeing circular reference issues, that probably means you're using JSON.stringify, which can cause this. That's an issue in your code, see https://stackoverflow.com/questions/11616630/how-can-i-print-a-circular-structure-in-a-json-like-format for more details on how to deal with this. Alternatively, in most environments you can just pass data directly without stringifying it, and `console.log` on your platform will probably do the sensible thing for you.

As a further option, you could create a plugin to handle this, by automatically stringifying content for you. I generally wouldn't encourage that, but if you'd like to be able to change global behaviour when logging then that's the way to do it: https://github.com/pimterry/loglevel#writing-plugins
