### ISSUE TITLE
Possibility to save log output to file

### ISSUE THREAD

**Issue by mjovanc** [pimterry/loglevel#175]
Is there some possibility to save the log output to a file through loglevel?

**Comment by Ryuno-Ki** [comment]
I could imagine via a plugin. Perhaps https://github.com/kutuluk/loglevel-plugin-remote ?

**Comment by mjovanc** [comment]
Thanks @Ryuno-Ki, I realized though I could just simply add this to my start script:

```json
"start": "node server.js >> output.log 2>&1",
```

**Comment by Ryuno-Ki** [comment]
Do you mind to close this issue then?
You've documented a solution for others who might ask themselves the same.

**Comment by mjovanc** [comment]
Absolutely. Closing the issue.
