### ISSUE TITLE
LogLevel `trace`, `debug` and `info` not shown anymore on Google Chrome

### ISSUE THREAD

**Issue by DanEEStar** [pimterry/loglevel#178]
The output of `log.trace(msg)`, `log.debug(msg)` and `log.info(msg)` is not shown anymore on the current version of Desktop Browsers. I am on MacOS 12.5

`log.warn(msg)` and `log.error(msg)` still work as expected.

I checked it today on Google Chrome 104, Brave 1.42 (based on Chrome 104), Firefox 104 and also Safari 15.6 -> They will only show messages from `warn` and `error`. All other level messages don't show...

The messages don't just to seem filtered out, at least I could not find a setting to enable them again in the browser.

I could swear that it was still working a few weeks ago on the then current version of Brave.

Am I the only on with this problem? A colleague of mine, also with MacOS, has the same problem...
Did something change on the working and specification of `console` lately?

**Comment by DanEEStar** [comment]
This is somewhat embarrassing...

The default log level seems to have been on `warn`.
When I set `log.enableAll()` the console starts to show `debug` and `info` messages. (`trace` is still hidden).

But did maybe somehow the default log level, or the handling of this, change in recent months on browsers?

**Comment by pimterry** [comment]
> But did maybe somehow the default log level, or the handling of this, change in recent months on browsers?

Hi @DanEEStar, I'm afraid not. I'm not aware of anything that could cause this and loglevel hasn't had any new changes published for quite a few months now. In some browsers there are  browser-configured loglevels which could hide certain outputs, controlled by settings in the console itself, so if you've changed that then it might've hidden messages unexpectedly?

Beyond that I'm not sure, but I don't think this is a loglevel problem I'm afraid.
