### ISSUE TITLE
Log to a file

### ISSUE THREAD

**Issue by brett-matson** [pimterry/loglevel#180]
Sorry, this is probably an obvious question: is there a way to get loglevel to write to a file?

Thanks in advance

**Comment by pimterry** [comment]
As a built-in feature, no. Loglevel intentionally doesn't include any kind of advanced features like this, it's out of scope.

It should be possible as a plugin on top of loglevel though (see https://github.com/pimterry/loglevel#plugins). From a quick google, it looks like somebody has implemented that here: https://github.com/infinum/loglevel-filesave.
