### ISSUE TITLE
Couldnt locate documention or plugins to format logged payload as JSON (compatible with Datadog etc)

### ISSUE THREAD

**Issue by gkatsanos** [pimterry/loglevel#186]
Hi, 

Looked into the documention, couldn't find any reference to formatters or even external plugins. I'm sure I didn't look close enough, any help would be appreciated.

( sidequestion: I saw you do not handle `Error` objects in the background so that's something that we should do in the application side with a utility function , follow up question: what's the added value to using a 3rd party library to log then? - I am not implying there's no value; just wondering if I should drop our internal Logger class/implementation and what would the gains be)

many thanks for your time! 

```js
class Logger {
  private errorToJson(error) {
    return Object.getOwnPropertyNames(error).reduce(function(result, key) {
        result[key] = error[key];
        return result;
    }, {});
  }

  info(payload, message: string) {
    this.log("info", payload, message)
  }

  warn(payload, message: string) {
    this.log("warn", payload, message)
  }

  error(payload, message: string) {
    if (payload instanceof Error) {
      payload = this.errorToJson(payload)
    }
    this.log("error", payload, message)
  }

  log(level, payload, message: string) {
    const span = this.getActiveSpan()
    const time = new Date().toISOString()
    const record = { time, level, payload, message }

    if (span) {
      tracer.inject(span.context(), formats.LOG, record)
    }
    process.stdout.write(`${JSON.stringify(record)}\n`)
  }

  getActiveSpan(): tracer.Span | undefined {
    return tracer.scope().active()
  }
}
```

**Comment by pimterry** [comment]
> Looked into the documention, couldn't find any reference to formatters or even external plugins.

See https://github.com/pimterry/loglevel#plugins.

> just wondering if I should drop our internal Logger class/implementation and what would the gains be

If you already have an internal logging system, you probably don't need this library. This is intended as a very lightweight zero-impact (doesn't affect stack traces) max-compatibility (works even in old browsers) logging tool, that's primarily useful as small upgrade to console.log itself.

It is absolutely possible to add things like custom formatting, and forwarding logs elsewhere, and all sorts on top, but if advanced logging features like that are your main goal then it's probably not the tool for you.

**Comment by gkatsanos** [comment]
@pimterry which tool would you recommend? (winston I guess, but the issue there is you can't have a uniform way of logging on browser/server which is an issue for several SSR/isomorphic apps (next, nuxt, astro)
