### ISSUE TITLE
The name of the file the log has been generated and the line number is broken when using a plugin

### ISSUE THREAD

**Issue by mustafaekim** [pimterry/loglevel#188]
Hello,

I've encountered an issue while implementing a plugin. When logging messages, the browser's console displays the name of the file where the logger is created, rather than the actual file where the log is generated. This also applies to the line number of the code.

Is there a way to use a plugin and ensure that the logs in the browser console accurately display the correct file name and line number of the code where the log is generated?

**Comment by pimterry** [comment]
Yes, this is documented in the README as the reason that most plugin features aren't built into loglevel itself: https://github.com/pimterry/loglevel#plugins

> Is there a way to use a plugin and ensure that the logs in the browser console accurately display the correct file name and line number of the code where the log is generated?

Depends on the plugin, but generally no. To correctly display the filename, the log call must be made directly on the corresponding console.log method, or on a bound version of the console.log method (which can be used to prefix arguments, but not to modify them). As soon as you have any kind of wrapper function around the call, the wrapper will appear in the stack trace.

If your behaviour can be implemented via `console.log.bind(console, ...)` then you might be able to do this (either modifying the plugin you're interested in or creating your own) but if you need a function wrapper then this is unavoidable. That's a browser limitation, so it's the same for loglevel and all other similar tools.

**Comment by mustafaekim** [comment]
Hello, thank you for the thorough explanation.
