### ISSUE TITLE
Awesome philosophy

### ISSUE THREAD

**Issue by nicholaswmin** [pimterry/loglevel#200]
This module has an awesome philosophy - love it.
I stopped installing npm modules a good while ago, trying to make do with what the runtime has, even if lacking a bit of bells and whistles in favor of zero-dependency, super fast builds and boots. It's awesome. 

These are the kinds of modules that I want to install. tries to make do with what's there, 0 bloat, known APIs, gets the job done, cya.

The only thing I (might) do different is drop support for older devices/browsers if it makes a difference in file/sizes maintenance and be alert to feature creep -  but I guess you guys know better.

Just dropping buy, no issues. Thanks.

**Comment by pimterry** [comment]
:heart: Thanks @nicholaswmin! :smile:
