### ISSUE TITLE
Add option to choose whether requirejs is used or not

### ISSUE THREAD

**Issue by edhgoose** [pimterry/loglevel#69]
I'll admit this is a bit of an edge case:

We have a JavaScript library which we're loading on our clients sites. We don't control our clients sites, but do control ours (of course).

We recently added loglevel to our library to help with diagnosing issues, and found that it works great (thx!), except on one client who uses RequireJS. Our workaround was to therefore strip out the bit of loglevel that adds requirejs, amd and so forth. Our log level now starts:

    !function(a,b){a.log=b()}(this ....

Instead of:

     !function(a,b){"object"==typeof module&&module.exports&&"function"==typeof require?module.exports=b():"function"==typeof define&&"object"==typeof define.amd?define(b):a.log=b()}(this ....

It would therefore be useful for us to disable the "load via RequireJS/AMD/etc" feature (in favour of loading 'normally') via a flag or something. Open to suggestions!

Thanks!

**Comment by pimterry** [comment]
Interesting, ok. I do think this is a bit of a strange case, so I'm not too keen to support it directly. There should be a few different things you can do to handle it yourself though:

* Use loglevel within require. Add it as a dep to the relevant code, or put in new blocks depending on it where necessary. This is definitely the 'right' way of doing it, if you can.

```javascript
require(['./path/to/loglevel.js', function (log) {
   log.warn("hi");
});
```

* Use require to make Loglevel global. Bit messy (nicer to just use loglevel with require directly), but quick and effective. Does have some async gotchas that you'll have to watch out for (log won't be available immediately, until the indeterminate time when RequireJS is finished loading it and setting it up.

```javascript
require(['./path/to/loglevel.js', function (log) {
  window.log = log;
});
```

* Disable Require briefly when loading loglevel, either with the below, or by just putting the script tag for loglevel above the script tag for RequireJS.

```html
<script>
window.disabledDefine = define;
window.define = undefined;
</script>
<script src="/path/to/loglevel.js"></script>
<script>
window.define = disabledDefine;
</script>
```

Does that help at all?

**Comment by edhgoose** [comment]
Interesting ideas. Totally agree this is an edge case, but good to have some ideas to think about.

Here's some thoughts:

1. Agree this is the correct way, but only one of our N clients uses require. We'd have to have something in our code saying if require do x, if amd do y, if neither do z. So it's slightly more complicated, but probably the correct way for us to do it.

2. We're actually using it in noConflict mode (we're creating one Global and everything we add to our clients resides within that, including the logging), but I like this is a potential alternative. I might give this one a try as it's the simplest for our use case.

3. We can't change the order of the scripts, because our client will decide that. But it's interesting to think of disabling it temporarily. This feels like quite a nice backup plan if 2 doesn't work.

Thank you for the ideas, I'm happy for you to close this if you're unlikely to support it.

**Comment by pimterry** [comment]
Closing this; I don't think I want to support this directly. If you do find a nice way to do this, either externally or in a small clean way within loglevel I'd be interested to hear it, but otherwise I'm going to leave this be for now. Thanks for raising it though, definitely an interesting point.
