### ISSUE TITLE
Get current logging level.

### ISSUE THREAD

**Issue by dmwyatt** [pimterry/loglevel#70]
For some operations it is good to know the current logging level.

For example, if you do string concatenation in your logging statements that are in sections of code that get called a lot, Javascript does the relatively-expensive string concatenation even if the current logging level won't actually output the string.

I think something like `log.getLevel()` would be useful so you could do the expensive operation only when needed.

**Comment by notthetup** [comment]
:+1:

**Comment by mroderick** [comment]
@dmwyatt you make a good argument. How implementing it and make a pull request?

**Comment by daniellmb** [comment]
+1

**Comment by madarche** [comment]
+1

**Comment by marcelboettcher** [comment]
+1 need it as well to init my plugin, which is done by setting the level at the moment. But I don't want to override the current level. Better would be an init / initPlugins method for that, but getting the current log level would provide me a work around.

**Comment by pimterry** [comment]
Hi @marcelboettcher; that sounds interesting, can you send me some more details on what you're trying to do, and why you need to log level to do so? There is a PR in for this now anyway, but I'd be interested to take a closer look if there's something that you need better support for to manage your plugin initialization.

**Comment by marcelboettcher** [comment]
Hey @pimterry, at the moment I need to set the log level after defining the plugin to register it, right? It just does not feel right to set any level for that reason as I want to stick to the level, which is set for a good reason.

Am I mixing things up here?

Looking forward to you bringing light into the darkness. Thx, Marcel

**Comment by pimterry** [comment]
Ah, I see, interesting. Yep, that makes sense. Once we've got the current level tracked though (as in the new related PR) this gets easier.

Would your issues be solved with an initPlugins() method, which basically just reset the level to the current level? I.e. equivalent to calling log.setLevel(log.getLevel()).

Alternatively, thoughts on moving from setting a `.methodFactory` field to instead have a `.setMethodFactory()` method, which automatically reset the levels for you to initialize your plugin? Neater, given that we need to do this, but not backward compatible unfortunately.

**Comment by marcelboettcher** [comment]
yes, initPlugins() would solve that, but your approach with .setMethodFactory() is much cleaner. You should still support the property .methodFactory for backward compatible, but mark it as depricated.

**Comment by Stexxen** [comment]
Slightly different use case for me. Something like ```log.isDebug()``` which returns true is debug messages are going to the console.

This is for debug code that is computational expensive, so I don't even want to execute it, instead of executing and then throwing it away.

This would be similiar the Java logback interface http://logback.qos.ch/apidocs/ch/qos/logback/classic/Logger.html

**Comment by madarche** [comment]
@Stexxen with #77 you would do the following:

    if (log.getLevel() <= log.levels.DEBUG) {
        // Do your computational expensive code
    }

**Comment by Stexxen** [comment]
ahhh ok, just to check, would <= in this situation mean DEBUG+TRACE or DEBUG+INFO+ERROR?

i.e are the levels Big Endian/Little Endian.

Might still be worth a wrapper function, as it would not be 100% clear when another developer reviews the code.

**Comment by madarche** [comment]
@Stexxen in this situation `<= ` means DEBUG+TRACE cf. https://github.com/pimterry/loglevel/blob/master/lib/loglevel.js#L116

This is true that this comparison is not 100% clear but it's generic and thus keeps the library code smaller. Personally I just need the "get current level" functionality and could live with a not perfectly clear condition since the context around would disambiguate the purpose.

**Comment by Stexxen** [comment]
@madarche True.
and thanks for the src link. 
S.
