### ISSUE TITLE
Any interest in stubbing/passingthrough other console methods?

### ISSUE THREAD

**Issue by daniellmb** [pimterry/loglevel#71]
I'd like to use a single consistent API to call other methods like `console.time` or `console.table` But I don't want those methods to fail in old browsers, and I don't want to litter my code with checks to see what's supported everywhere. So I'm interested in adding something like this (from Ben Alman's debug lib). If not here, I'll just fork loglevel and add it for just me :)

```javascript
// Pass these methods through to the console if they exist, otherwise just
// fail gracefully. These methods are provided for convenience.
pass_methods = 'assert clear count dir dirxml exception group groupCollapsed groupEnd profile profileEnd table time timeEnd trace'.split(' '),
idx = pass_methods.length,

while (--idx >= 0) {
  (function (method) {

      // Generate pass-through methods. These methods will be called, if they
      // exist, as long as the logging level is non-zero.
      that[method] = function () {
          log_level !== 0 && con && con[method]
            && con[method].apply(con, arguments);
      }

  })(pass_methods[idx]);
}
```

Thoughts?

**Comment by pimterry** [comment]
In principle, sure. With a few caveats: they need to work sensibly with the set level (tricky problem: group should probably work at any level, but should time/timeEnd?), and they need to work consistently in every browser that supports them (have all the browsers implemented these the same way?).

As long as it fits in that, and it doesn't make the library vastly more complicated then I'd be happy to merge it.

**Comment by daniellmb** [comment]
I was thinking of something simple like this (untested sudo code)

```javascript
var passthrough = "assert clear count dir dirxml exception group groupCollapsed groupEnd markTimeline profile profileEnd table time timeEnd timeStamp timeline timelineEnd";
var index = passthrough.length;

while (--index >= 0) {
  (function (method) {
      // wrap the console method
      self[prop] = function () {
        // call the method only when loglevel is not silent
        if (level !== self.levels.SILENT) {
          console[prop].apply(console, arguments);
        }
      };
  })(passthrough[index]);
}
```

**Comment by daniellmb** [comment]
I'm going to go with forking.
