### ISSUE TITLE
New NPM release?

### ISSUE THREAD

**Issue by idolizesc** [pimterry/loglevel#79]
Hey - love the library!

I'd like to take advantage of the new `setDefaultLevel()` method -- any chance we can get a new release on npm soon with that functionality?

Thanks :+1:

**Comment by pimterry** [comment]
Thanks! There's a few more open changes that I'd like to get finalized and merged in the short term, but there'll definitely be one coming within the next few weeks.

**Comment by davetayls** [comment]
hey @pimterry what's the latest with getting this on npm?

**Comment by pimterry** [comment]
Hi @davetayls, done now! There's a 1.4.0 release out including all the recent changes.

**Comment by davetayls** [comment]
Thanks!
