### ISSUE TITLE
Not support for typescript

### ISSUE THREAD

**Issue by KingWu** [pimterry/loglevel#97]
typings install --global --save dt~logLevel

typings ERR! message Unable to find "logLevel" ("dt") in the registry.

**Comment by pimterry** [comment]
Should work, I think that's just a typo with the capital 2nd L in `logLevel` (should be `loglevel`). Try:

```javascript
typings install --global --save dt~loglevel
```

**Comment by pimterry** [comment]
I'm going to go ahead and close this, since I'm pretty sure that solves it. Let me know if you still have any trouble.

**Comment by anwfr** [comment]
hi,
You can find usage example of loglevel with typescript + webpack/typings2 here:
https://github.com/anwfr/loglevel-ts
