### ISSUE TITLE
Example plugin loses filename and line numbers

### ISSUE THREAD

**Issue by tauren** [pimterry/loglevel#98]
Without a plugin, loglevel shows the correct file and line number. Bravo! 

However, when I use the example plugin in the readme, the console always indicates that the message is from the `rawMethod('Newsflash: ' + message)` line in the plugin. This makes it much more difficult to trace the actual log location which decreases the utility of using loglevel.

It appears that internally, you are binding to the `console` functions which I assume enables the correct line number to be displayed. So perhaps plugins could do something similar? Is there any chance you could update the example plugin to illustrate how to solve this problem?

**Comment by pimterry** [comment]
Indeed it does. Sorry, but that's an unavoidable problem, which is why the functionality that these plugins add isn't baked in.

If you want to do *anything* dynamically at the point where a log function is called, then you have to wrap the function, and that means you mess up your stacktrace. It's just how JavaScript works I'm afraid, and you can't get out of it afaik (although do let me know if you have any clever ideas). Changes you can make in advance to the function calls can be done without breaking things (e.g. you can change logging functions for no-ops, as loglevel does to change the enabled logging levels, or you can prefixing a message with fixed extra arguments using `bind`), but those are pretty niche cases.

Almost anything interesting you might want to in a plugin requires that you breaking file & line number goodness, and there's nothing you can do about it. Sorry!

**Comment by tauren** [comment]
Thanks for the clarification.

I have been toying with building a library that will help output CSS styled logs. For instance:

```
console.log('%cThis is large blue text', 'font-size: large; color: blue')
```

I'm not sure what the library API will look like yet, as it will be determined by what is feasible, but perhaps it could be something like this:

```
log.debug(large(blue('This is large blue text')))
```

However, to make this happen, I need logic that determines if the first argument is a primitive or is an instance of my tool. If it is an instance of my tool, then the first argument needs to have `%c` prepended to it and a second argument containing the CSS string needs to be inserted.

It sounds like it probably isn't possible, as it would require dynamically changing `console.log` arguments for each call.  Do you have any ideas on how to get this use case working while still maintaining line numbers?

**Comment by tauren** [comment]
Actually, what if the API was something like this instead:

```
log.debug.largeBlue('This is large blue text')
log.info.highlight('This is highlighted text')
```

I should be able to dynamically generate lots of methods in advance that are bound to the `console` methods. And I could bind a second argument containing CSS to each of these. But I'd still need to figure out how to add the `%c` to the first argument.

Originally I was thinking of doing something more like the `colors` module does, but I don't think this would be possible give the `console.log` limitations:

```
log.debug('This is large blue text'.large.blue)
```

**Comment by pimterry** [comment]
That's closer, but you still have to transform the message string inside the logging method, which is the key problem, and you can't add suffixed arguments with `bind` (afaik), you can only prefix them. Annoying, I know.

To make this work, I think you have to do all your transformation before the call to the underlying browser's logging method. If your transformation code is ever the thing that calls the underlying methods, then that's where the stacktrace will start.

The easy answer is to do something more like:

```javascript
log.info(format("My message"), largeBlue())
```

There all the transform happens completely before the call to log.info. Obvious that's not quite as lovely an API though. You could add [spread](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator#Rest_operator) to this in ES6 to arguably improve it:

```javascript
log.info(...largeBlue("My message"))
```

There `largeBlue` would return two strings as an array, and those would become the two separate arguments to log.info. That only works where this is supported though - Edge (but not IE), Chrome 46+, Firefox 27+. Most people's browsers, but not all browsers, and it's a syntax error in unsupported browsers so you can't polyfill it (although Babel etc could pre-compile it away).

Alternatively you could take a whole different tack and look at [Chrome object console formatters](https://docs.google.com/document/d/1FTascZXT9cxfetuPRT2eXPQKXui4nWFivUnS_335T3U/preview). Your library then transforms logged objects/strings into a single object that includes a bunch of formatting info, and then you can provide a formatter (which the relevant devs must install locally) than nicely transforms that object into any representation you like. A totally different approach, with a different set of downsides, but it's an interesting option.

**Comment by tauren** [comment]
@pimterry Great feedback! I've learned a lot about this since posting, and this is essentially the same conclusion I came to. However, since I am using Babel, your suggestion of using ES6 `spread` is interesting. But I'm certainly not thrilled with any of the APIs you or I have considered.

Thanks again for your thoughts!

**Comment by pimterry** [comment]
Yeah, it's frustrating, but there's no other way to avoid appearing in the stack when the log function gets called I think. Good luck!

**Comment by tauren** [comment]
I just created a babel plugin that should make it possible to do most of the things I would like. It is very *alpha* quality at the moment, but thought you might be interested in it:
https://github.com/tauren/babel-plugin-console-log
