### ISSUE TITLE
Correct usage with webpack, how?

### ISSUE THREAD

**Issue by oka-garaio** [pimterry/loglevel#99]
Hi,

I'd like to use loglevel in a typescript/webpack project. I've installed it via npm install loglevel.

then I require it with `import log from "loglevel"` and also tried to use `window.log = require("loglevel")` but none of this method work. `log` is always `undefined`

Do you have any tips how I got that working?

**Comment by oka-garaio** [comment]
It works when I use it like this `import * as log from "loglevel";`.

**Comment by pimterry** [comment]
Interesting - I don't know webpack that well, so I can't really help you out here, but sounds like you've found your solution anyway :-). I'll close this for now, feel free to comment if there's anything else that needs looking at.

**Comment by anwfr** [comment]
hi,
You can find usage example of loglevel with typescript + webpack/typings2 here:
https://github.com/anwfr/loglevel-ts
